spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.108.25.63:3306/urbanSense?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: Liuhangji0904

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.cqupt.urbansense.bean
