spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    host: 47.108.25.63
    port: 6379
    password: leadnews
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.108.25.63:3306/urbanSense?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: Liuhangji0904

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.cqupt.urbansense.bean

minio:
  accessKey: minio
  secretKey: minio123
  bucket: urbansense
  endpoint: http://47.108.25.63:9001
  readPath: http://47.108.25.63:9001
wechat:
  appid: wx4ce224399a62cd41
  secret: f4cc1174c0ce61e0378030edb7c519ba
redisson:
  password: leadnews
  address: redis://47.108.25.63:6379
